=== Gouzmixd/dsbhtml/DSBprojetPartie2/Q7/Q7-DTD.dtd
<!ELEMENT racine (glossaire?,jeuvideo*,glossaire*)>

<!ELEMENT glossaire (mot)+>
<!ELEMENT mot (#PCDATA)>
<!ATTLIST mot def CDATA #REQUIRED>
<!ATTLIST glossaire auteur CDATA #IMPLIED>

<!ELEMENT base (jeuvideo,glossaire*)>


<!ELEMENT jeuvideo (nom,date,notejvc?,nomdev,nomedi)>
<!ATTLIST jeuvideo id CDATA #REQUIRED>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT notejvc (#PCDATA)>
<!ELEMENT pegi (#PCDATA)>
<!ELEMENT recompense (#PCDATA)>
<!ELEMENT nomdev (#PCDATA)>
<!ELEMENT nomedi (#PCDATA)>

=== Gouzmixd/dsbhtml/DSBprojetPartie2/Q8b-XML.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE carnet SYSTEM "Q7-DTD.dtd">
<racine>
	<glossaire>
		<mot def="MCD">MCD (modèle conceptuel de données)</mot>
		<mot def="MOCODO">MOCODO (Modélisation Conceptuelle de Données)</mot>
	</glossaire>
	<jeuvideo id="RMGE01">
		<nom>Super Mario Galaxy</nom>
		<date>2007-11-01</date>
		<notejvc>19/20</notejvc>
		<nomdev>Nintendo</nomdev>
		<nomedi>Nintendo</nomedi>
	</jeuvideo>
</racine>

=== Gouzmixd/dsbhtml/DSBprojetPartie2/Q8/Q8b-XML.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE carnet SYSTEM "Q7-DTD.dtd">
<?xml-stylesheet href="C:\Users\mattm\dsbhtml\DSBprojetPartie2\Q10\Q10a-XML.css"?>
<racine>
	<glossaire>
		<mot def="MCD">MCD (modèle conceptuel de données)</mot>
		<mot def="MOCODO">MOCODO (Modélisation Conceptuelle de Données)</mot>
	</glossaire>
	<jeuvideo id="RMGE01">
		<nom>Super Mario Galaxy</nom>
		<date>2007-11-01</date>
		<notejvc>19/20</notejvc>
		<nomdev>Nintendo</nomdev>
		<nomedi>Nintendo</nomedi>
	</jeuvideo>
</racine>
